-- =====================================================
-- ADD SECURITY QUESTIONS AND ACCOUNT LOCK FIELDS
-- Run this SQL script to add security question functionality
-- =====================================================

USE lawfirm_db;

-- Add security question fields to ADVOCATE table
ALTER TABLE ADVOCATE 
ADD COLUMN IF NOT EXISTS SecurityQuestion VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS SecurityAnswer VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS IsLocked BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS FailedAttempts INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS LockedAt DATETIME DEFAULT NULL;

-- Add security question fields to RECEPTIONIST table
ALTER TABLE RECEPTIONIST 
ADD COLUMN IF NOT EXISTS SecurityQuestion VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS SecurityAnswer VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS IsLocked BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS FailedAttempts INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS LockedAt DATETIME DEFAULT NULL;

-- Add security question fields to CLIENT_AUTH table
ALTER TABLE CLIENT_AUTH 
ADD COLUMN IF NOT EXISTS SecurityQuestion VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS SecurityAnswer VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS IsLocked BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS FailedAttempts INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS LockedAt DATETIME DEFAULT NULL;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_advocate_locked ON ADVOCATE(IsLocked);
CREATE INDEX IF NOT EXISTS idx_receptionist_locked ON RECEPTIONIST(IsLocked);
CREATE INDEX IF NOT EXISTS idx_client_auth_locked ON CLIENT_AUTH(IsLocked);
